### ISSUE TITLE
iOS: Animation always scrolling on the same side when the position is updated in code behind.

### ISSUE THREAD

**Issue by Jean-RochSDX** [microspaze/CarouselView.Maui#1]
When the position is updated in code behind, the animation will always be the same and want go back and forth if the item the position is updated by the code behind. The bug can pe reproduced by running the sample of the repository on an iOS device. When scrolling the horizontal Carousel back and forth, the vertical Carousel will be updated but always using the animation in the same direction. The same can be observed if you scroll the vertical Carousel back and forth, then the horizontal Carousel will update it's content but always using the same side for the animation.

**Comment by microspaze** [comment]
@Jean-RochSDX This bug has been fixed in the version 1.0.5: [CarouselView.Maui 1.0.5](https://www.nuget.org/packages/CarouselView.Maui/1.0.5)

**Comment by Jean-RochSDX** [comment]
Hi, just tried it and can confirm that it is fixed. Thanks a lot!
